In [1]:
import sqlite3

import pandas as pd
from IPython.display import display

In [2]:
conn = sqlite3.connect('../loteca/data/raw/betexplorer/db.sqlite3')
betexp = pd.read_sql_query('SELECT * FROM matches', conn)
conn.close()

betexp.head()

,id,url,league_category,league_name,league_year,teamH,teamA,date,score,scoremod
0,GCjoqXpn,/soccer/world/world-cup-women/israel-w-finland...,world,World Cup Women,2019,Israel W,Finland W,22.01.2018,0:0,
1,xMispDVu,/soccer/world/world-cup-women/spain-w-austria-...,world,World Cup Women,2019,Spain W,Austria W,28.11.2017,4:0,
2,xnyYIzXt,/soccer/world/world-cup-women/portugal-w-italy...,world,World Cup Women,2019,Portugal W,Italy W,28.11.2017,0:1,
3,pjD4z32E,/soccer/world/world-cup-women/romania-w-moldov...,world,World Cup Women,2019,Romania W,Moldova W,28.11.2017,3:1,
4,nZiE6CQJ,/soccer/world/world-cup-women/netherlands-w-ir...,world,World Cup Women,2019,Netherlands W,Ireland W,28.11.2017,0:0,

In [3]:
# split urls from dataframe

urls = betexp.url
urls = 'http://www.betexplorer.com' + urls

betexp = betexp.drop('url', axis=1)
display(betexp.head())
print(urls[0])

,id,league_category,league_name,league_year,teamH,teamA,date,score,scoremod
0,GCjoqXpn,world,World Cup Women,2019,Israel W,Finland W,22.01.2018,0:0,
1,xMispDVu,world,World Cup Women,2019,Spain W,Austria W,28.11.2017,4:0,
2,xnyYIzXt,world,World Cup Women,2019,Portugal W,Italy W,28.11.2017,0:1,
3,pjD4z32E,world,World Cup Women,2019,Romania W,Moldova W,28.11.2017,3:1,
4,nZiE6CQJ,world,World Cup Women,2019,Netherlands W,Ireland W,28.11.2017,0:0,

http://www.betexplorer.com/soccer/world/world-cup-women/israel-w-finland-w/GCjoqXpn/

In [4]:
betexp.date = pd.to_datetime(betexp.date, dayfirst=True)
betexp.score = betexp.score.str.strip()

In [5]:
# the scores are okay
sorted(betexp.score.unique())

['',
 '0:0',
 '0:1',
 '0:10',
 '0:11',
 '0:12',
 '0:13',
 '0:14',
 '0:15',
 '0:16',
 '0:17',
 '0:18',
 '0:19',
 '0:2',
 '0:21',
 '0:22',
 '0:23',
 '0:24',
 '0:25',
 '0:27',
 '0:3',
 '0:4',
 '0:5',
 '0:6',
 '0:7',
 '0:8',
 '0:9',
 '10:0',
 '10:1',
 '10:2',
 '10:9',
 '11:0',
 '11:1',
 '11:2',
 '11:3',
 '12:0',
 '12:1',
 '12:2',
 '12:3',
 '13:0',
 '13:1',
 '13:2',
 '13:3',
 '14:0',
 '14:1',
 '14:2',
 '15:0',
 '15:1',
 '16:0',
 '16:1',
 '17:0',
 '17:1',
 '18:0',
 '19:0',
 '19:5',
 '1:0',
 '1:1',
 '1:10',
 '1:11',
 '1:12',
 '1:13',
 '1:14',
 '1:15',
 '1:16',
 '1:17',
 '1:2',
 '1:23',
 '1:3',
 '1:4',
 '1:5',
 '1:6',
 '1:7',
 '1:8',
 '1:9',
 '20:0',
 '21:0',
 '22:0',
 '23:0',
 '25:0',
 '2:0',
 '2:1',
 '2:10',
 '2:11',
 '2:15',
 '2:2',
 '2:3',
 '2:4',
 '2:5',
 '2:6',
 '2:7',
 '2:8',
 '2:9',
 '3:0',
 '3:1',
 '3:10',
 '3:11',
 '3:2',
 '3:3',
 '3:4',
 '3:5',
 '3:6',
 '3:7',
 '3:8',
 '3:9',
 '4:0',
 '4:1',
 '4:2',
 '4:3',
 '4:4',
 '4:5',
 '4:6',
 '4:7',
 '4:8',
 '4:9',
 '5:0',
 '5:1',
 '5:2',
 '5:3',
 '5:4',
 '5:5',
 '5:6',
 '5:7',
 '5:8',
 '6:0',
 '6:1',
 '6:2',
 '6:3',
 '6:4',
 '6:5',
 '6:6',
 '6:7',
 '7:0',
 '7:1',
 '7:2',
 '7:3',
 '7:4',
 '7:5',
 '8:0',
 '8:1',
 '8:2',
 '8:3',
 '8:4',
 '8:8',
 '9:0',
 '9:1',
 '9:2',
 '9:3',
 '9:4']

In [6]:
# and scoremods?
scoremods = sorted(betexp.scoremod.unique())
scoremods

['', 'ABN.', 'AWA.', 'CAN.', 'ET', 'INT.', 'PEN.', 'POSTP.', 'WO.']

In [7]:
betexp.scoremod.value_counts()

          289761
PEN.        2274
CAN.        1833
ET          1676
AWA.         411
POSTP.       158
ABN.          77
WO.           26
INT.           3
Name: scoremod, dtype: int64

In [8]:
for smod in scoremods:
    print('{: <8}'.format(smod), urls[betexp.scoremod == smod].iloc[-1])

         http://www.betexplorer.com/soccer/brazil/copa-do-nordeste/confianca-treze-pb/lGJofK20/
ABN.     http://www.betexplorer.com/soccer/england/professional-development-league/charlton-u23-crystal-palace-u23/p2BiuoAI/
AWA.     http://www.betexplorer.com/soccer/germany/oberliga-schleswig-holstein/dornbreite-lubeck-ntsv-strand-08/6T9bUftH/
CAN.     http://www.betexplorer.com/soccer/england/premier-league-cup/chesterfield-u23-wigan-u23/t2dJIAeo/
ET       http://www.betexplorer.com/soccer/england/fa-cup-women/liverpool-feds-w-bolton-w/zJrKfzjr/
INT.     http://www.betexplorer.com/soccer/world/club-friendly-2010/fsv-frankfurt-metz/UVkYbfUa/
PEN.     http://www.betexplorer.com/soccer/brazil/copa-do-brasil/vila-nova-fc-joinville/23VxWzfa/
POSTP.   http://www.betexplorer.com/soccer/england/wsl-2-women/brighton-w-watford-w/dCBGBbYi/
WO.      http://www.betexplorer.com/soccer/england/fa-cup-women/plymouth-w-basingstoke-w/Qqcl0dSK/

### Score Modifiers

Usual:

- ET: After Extra Time (score refers to score after the extra time)
- PEN: After Penalties (score example: `2:1` refers to `(1:1, 0:0, 3:2)`)

No score:  

- POSTP: Postponed
- WO: Walkover - TEAM

With score:  

- INT: Interrupted (only happened in 3 matches)

Some with score, some without:

- ABN: Abandoned
- AWA: Awarded
- CAN: Canceled
- INT: Interrupted

**TODO**: understand what happens to the loteca score in these matches.

In [9]:
# league_year
betexp.league_year.value_counts().sort_index()

2008/2009    14643
2009          4338
2009/2010    15915
2010          5726
2010/2011    17090
2011          8240
2011/2012    21036
2012          7617
2012/2013    23131
2013          8417
2013/2014    25996
2014          8248
2014/2015    26202
2015          8518
2015/2016    26164
2016          9350
2016/2017    27482
2017         10470
2017/2018    23365
2018          4050
2019           221
Name: league_year, dtype: int64

In [10]:
print(urls.loc[32436])

http://www.betexplorer.com/soccer/brazil/serie-b-2011/barueri-portuguesa/4rHNNkEH/

In [11]:
# league categories

betexp.groupby('league_category').count()

,id,league_name,league_year,teamH,teamA,date,score,scoremod
league_category,,,,,,,,
brazil,19609,19609,19609,19609,19609,19609,19609,19609
england,63029,63029,63029,63029,63029,63029,63029,63029
europe,17285,17285,17285,17285,17285,17285,17285,17285
france,22053,22053,22053,22053,22053,22053,22053,22053
germany,55491,55491,55491,55491,55491,55491,55491,55491
italy,38998,38998,38998,38998,38998,38998,38998,38998
south-america,3050,3050,3050,3050,3050,3050,3050,3050
spain,32409,32409,32409,32409,32409,32409,32409,32409
world,44295,44295,44295,44295,44295,44295,44295,44295